import { z } from "zod";
import { ComfyPrompt, Workflow } from "../../src/types";

/**
 * ACE-Step 1.5 BuildInPublic Ambient Techno Soundtrack
 *
 * Generates ambient techno tracks with vocals where the lyrics describe
 * what was shipped. Used by the /render-buildinpublic pipeline.
 *
 * Input: lyrics.json from generate-lyrics.ts (caption + structured lyrics)
 * Output: MP3 audio file (~30-60 seconds)
 *
 * ComfyUI Node Flow (same as music-for-mood.ts):
 * CheckpointLoader → ModelSamplingAuraFlow → TextEncodeAceStepAudio1.5 →
 * EmptyAceStep1.5LatentAudio → KSampler → VAEDecodeAudio → SaveAudioMP3
 */

const RequestSchema = z.object({
  // Core inputs — generated by generate-lyrics.ts
  caption: z.string()
    .describe("ACE-Step style caption (e.g., 'ambient techno, ethereal vocals, deep bass')"),

  lyrics: z.string()
    .describe("Structured lyrics with [verse]/[chorus]/[bridge] tags"),

  bpm: z.number().int().min(80).max(160)
    .default(128)
    .describe("Beats per minute (ambient techno: 120-135)"),

  duration: z.number().int().min(15).max(120)
    .default(45)
    .describe("Audio duration in seconds"),

  key_scale: z.string()
    .default("A minor")
    .describe("Musical key (e.g., 'A minor', 'C major')"),

  // Generation parameters
  seed: z.number().int()
    .optional()
    .default(() => Math.floor(Math.random() * 1000000000000000))
    .describe("Random seed for reproducibility"),

  steps: z.number().int().min(1).max(50)
    .optional()
    .default(8)
    .describe("Sampling steps (8 for turbo model)"),

  cfg_scale: z.number().min(1).max(20)
    .optional()
    .default(3.5)
    .describe("Classifier-free guidance scale"),

  sampler_name: z.string()
    .optional()
    .default("euler")
    .describe("Sampler algorithm"),

  scheduler: z.string()
    .optional()
    .default("simple")
    .describe("Scheduler for sampling"),

  denoise: z.number().min(0.1).max(1.0)
    .optional()
    .default(1.0)
    .describe("Denoising strength (1.0 = full generation)"),

  checkpoint_name: z.string()
    .optional()
    .default("ace_step_1.5_turbo_aio.safetensors")
    .describe("ACE-Step 1.5 checkpoint model name"),

  // Language and time signature
  language: z.string()
    .optional()
    .default("en"),

  time_signature: z.string()
    .optional()
    .default("4"),
});

type InputType = z.infer<typeof RequestSchema>;

function generateWorkflow(input: InputType): ComfyPrompt {
  const filenamePrefix = `bip_${input.bpm}bpm_${Date.now()}`;

  return {
    // Node 1: Load ACE-Step checkpoint
    "1": {
      inputs: {
        ckpt_name: input.checkpoint_name,
      },
      class_type: "CheckpointLoaderSimple",
      _meta: { title: "Load ACE-Step 1.5 Checkpoint" },
    },

    // Node 2: Model Sampling (AuraFlow)
    "2": {
      inputs: {
        model: ["1", 0],
        shift: 3.0,
      },
      class_type: "ModelSamplingAuraFlow",
      _meta: { title: "Model Sampling (AuraFlow)" },
    },

    // Node 3: Empty latent audio
    "3": {
      inputs: {
        seconds: input.duration,
        batch_size: 1,
      },
      class_type: "EmptyAceStep1.5LatentAudio",
      _meta: { title: `Empty Latent Audio (${input.duration}s)` },
    },

    // Node 4: Encode caption + lyrics
    "4": {
      inputs: {
        clip: ["1", 1],
        seed: input.seed,
        duration: input.duration,
      },
      class_type: "TextEncodeAceStepAudio1.5",
      _meta: { title: "Encode BIP Prompt (ACE-Step 1.5)" },
      widgets_values: [
        input.caption,
        input.lyrics,
        input.seed,
        "fixed",
        190,
        input.bpm,
        input.time_signature,
        input.language,
        input.key_scale,
      ],
    },

    // Node 5: Zero out conditioning
    "5": {
      inputs: {
        conditioning: ["4", 0],
      },
      class_type: "ConditioningZeroOut",
      _meta: { title: "Zero Out Conditioning" },
    },

    // Node 6: KSampler — generate audio
    "6": {
      inputs: {
        seed: input.seed,
        steps: input.steps,
        cfg: input.cfg_scale,
        sampler_name: input.sampler_name,
        scheduler: input.scheduler,
        denoise: input.denoise,
        model: ["2", 0],
        positive: ["4", 0],
        negative: ["5", 0],
        latent_image: ["3", 0],
      },
      class_type: "KSampler",
      _meta: { title: "KSampler (Audio Generation)" },
    },

    // Node 7: VAE Decode — latent to audio
    "7": {
      inputs: {
        samples: ["6", 0],
        vae: ["1", 2],
      },
      class_type: "VAEDecodeAudio",
      _meta: { title: "VAE Decode Audio" },
    },

    // Node 8: Save as MP3
    "8": {
      inputs: {
        filename_prefix: filenamePrefix,
        audio: ["7", 0],
      },
      class_type: "SaveAudioMP3",
      _meta: { title: "Save BIP Soundtrack (MP3)" },
    },
  };
}

const workflow: Workflow = {
  RequestSchema,
  generateWorkflow,
  summary: "ACE-Step 1.5 BuildInPublic Ambient Techno Soundtrack",
  description:
    "Generate ambient techno tracks with vocals for #BuildInPublic videos. " +
    "Lyrics describe shipped features, test results, and the Agentosaurus mission. " +
    "Input: caption + structured lyrics from generate-lyrics.ts. " +
    "Output: 30-60 second MP3 at 128 BPM. Uses ACE-Step 1.5 Turbo (8 steps).",
};

export default workflow;
